### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by mooncityorg** [Charles-Chrismann/Charles-Chrismann#334]
Thanks for following my github
https://github.com/mooncityorg

I recently create discord server for github users.

We can co-operate each other by learning new tech, adding star and fork others github repository.
If you want to join, I will drop the invite link here.
Also you can invite your friends here
https://discord.gg/qwQ7S6ZP
Thanks Mooncity

**Comment by Charles-Chrismann** [comment]
See https://github.com/Charles-Chrismann#a-classic-wordle
